server:
  port: 8080
  servlet:
    context-path: /blockchain-api

# Hyperledger Fabric Network Configuration
fabric:
  msp-id: Org1MSP
  channel-name: mychannel
  chaincode-name: basic
  peer-endpoint: localhost:7051
  ca-server-endpoint: https://localhost:7054
  override-auth: peer0.org1.example.com

  # File Paths
  crypto-path: ./org1.example.com
  cert-dir-path: ./creds/certs
  key-dir-path: ./creds/keys
  csr-dir-path: ./creds/csrs
  tls-cert-path: peers/peer0.org1.example.com/tls/ca.crt

  # Timeout Configuration (in seconds)
  timeout:
    evaluate: 5
    endorse: 15
    submit: 5
    commit: 60

  # Transaction messages
  messages:
    submit-success: Transaction submitted successfully
    query-success: Query executed successfully
    submit-error: Failed to submit transaction
    query-error: Failed to query blockchain

# HSM Configuration
hsm:
  name: ForFabric
  library: /usr/lib/x86_64-linux-gnu/softhsm/libsofthsm2.so
  slot: 1681257824
  pin: 98765432
  signature:
    algorithm: NONEwithECDSA
    provider: SunPKCS11-ForFabric

# CA Admin Configuration
ca-admin:
  name: admin
  password: adminpw
  org-name: Org1
  cert-path: ./creds/certs/CaAdminOrg1_cert.pem
  key-path: ./creds/keys/CaAdminOrg1_priv.pem

# File Management
file:
  certs:
    dir: ./creds/certs/
  keys:
    dir: ./creds/keys/
  csrs:
    dir: ./creds/csrs/
  cert-suffix: _cert.pem
  priv-key-suffix: _priv.pem
  csr-suffix: _csr.pem

# Crypto Configuration
crypto:
  hash-algorithm: SHA-256
  signature-algorithm: SHA256withECDSA
  ec-curve: secp256r1
  
# User and Admin Configuration
user:
  affiliation: org1.department1
  max-enrollments: -1
  
admin:
  attribute:
    name: admin
    value: true
    
# API Response Messages
api:
  messages:
    admin-register-success: Admin registered successfully
    user-register-success: User registered successfully
    transaction-submit-success: Transaction submitted successfully
    query-success: Query executed successfully

logging:
  level:
    root: INFO
    com.example.blockchain: DEBUG
    org.hyperledger: INFO

spring:
  application:
    name: fabric-blockchain-sample
